Alix Milan/Alix Milan/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Alix_Milan.Models
{
    public class Category
    {
        [Required]
        public int ID {  get; set; }

        [Required]
        public string Name { get; set; }
        public int Order { get; set; }

        public byte[] ImageBytes { get; set; }
    }
}

Alix Milan/Alix Milan/Models/Kit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Alix_Milan.Models
{
    public class Kit
    {        
        public int ID { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Description { get; set; }

        [Required]
        public decimal Price { get; set; }

        [Required]
        public int Order { get; set; }

        public IEnumerable<KitItem> KitItems { get; set; }

        [Required]
        public byte[] ImageBytes { get; set; }   
    }
}

Alix Milan/Alix Milan/Models/KitItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Alix_Milan.Models
{
    public class KitItem
    {
        public int ID { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Description { get; set; }

        [Required]
        public decimal Price { get; set; }

        [Required]
        public int Order { get; set; }
        
        public Kit Kit { get; set; }

        public int? KitId { get; set; }

        [Required]
        public Category Category { get; set; }

        public int CategoryId { get; set; }

        [Display(Name="Sub-category")]
        public SubCategory SubCategory { get; set; }

        public int? SubCategoryId { get; set; }

        [Required]
        public byte[] ImageBytes { get; set; }
    }
}

Alix Milan/Alix Milan/Controllers/KitHireController.cs
using Alix_Milan.Models;
using Alix_Milan.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Alix_Milan.Controllers
{
    [AllowAnonymous]
    public class KitHireController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: KitHire
        public ActionResult Index()
        {
            return View(new KitHireModel
                {
                     Categories = db.Categories.OrderBy(c => c.Order),
                     Kits = db.Kits.OrderBy(k => k.Order)
                });
        }

        public ActionResult Kit(string kitName)
        {
            var kit = db.Kits.SingleOrDefault(k => k.Name == kitName);

            if (kit == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var kitModel = new KitModel
            {
                ID = kit.ID,
                Name = kit.Name,
                Description = kit.Description,
                Price = kit.Price,
                KitItems = db.KitItems.Where(ki => ki.KitId == kit.ID),
                ImageBytes = kit.ImageBytes

            };

            return View(kitModel);
        }

        public ActionResult Category(string categoryName)
        {
            var category = db.Categories.SingleOrDefault(c => c.Name == categoryName);

            if (category == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var categoryId = category.ID;
            var categoryModel = new KitHireCategoryModel
            {
                Name = category.Name,
                SubcategoryKitItems = GetSubcategoryKitItems(categoryId),
                MiscKitItems = GetMiscKitItems(categoryId),
                ImageBytes = category.ImageBytes
            };

            return View(categoryModel);
        }

        public ActionResult KitItem(string kitItemName)
        {
            var kitItem = db.KitItems.SingleOrDefault(c => c.Name == kitItemName);

            if (kitItem == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var kitItemModel = new KitItemModel
            {
                Name = kitItem.Name,
                Description = kitItem.Description,
                Price = kitItem.Price,
                ImageBytes = kitItem.ImageBytes
            };

            return View(kitItemModel);
        }

        private Dictionary<SubCategory, IEnumerable<KitItem>> GetSubcategoryKitItems(int categoryId)
        {
            var subcategoryKitItemsDictionary = new Dictionary<SubCategory, IEnumerable<KitItem>>();

            foreach (var subcategory in db.SubCategories.Where(sc => sc.CategoryId == categoryId).OrderBy(c => c.Order).ToList())
            {
                subcategoryKitItemsDictionary.Add(subcategory, db.KitItems.Where(ki => ki.SubCategoryId == subcategory.ID));
            }

            return subcategoryKitItemsDictionary;
        }

        private IEnumerable<KitItem> GetMiscKitItems(int categoryId)
        {
            return db.KitItems.Where(ki => ki.CategoryId == categoryId).Where(ki => ki.SubCategoryId.HasValue == false);
        }
    }
}

Alix Milan/Alix Milan/Controllers/KitItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Alix_Milan;
using Alix_Milan.Models;

namespace Alix_Milan.Controllers
{
    public class KitItemsController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: KitItems
        public ActionResult Index()
        {
            return View(db.KitItems.ToList());
        }

        // GET: KitItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KitItem kitItem = db.KitItems.Find(id);
            if (kitItem == null)
            {
                return HttpNotFound();
            }
            return View(kitItem);
        }

        // GET: KitItems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: KitItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Description")] KitItem kitItem)
        {
            if (ModelState.IsValid)
            {
                db.KitItems.Add(kitItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kitItem);
        }

        // GET: KitItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KitItem kitItem = db.KitItems.Find(id);
            if (kitItem == null)
            {
                return HttpNotFound();
            }
            return View(kitItem);
        }

        // POST: KitItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description")] KitItem kitItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kitItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kitItem);
        }

        // GET: KitItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KitItem kitItem = db.KitItems.Find(id);
            if (kitItem == null)
            {
                return HttpNotFound();
            }
            return View(kitItem);
        }

        // POST: KitItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            KitItem kitItem = db.KitItems.Find(id);
            db.KitItems.Remove(kitItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Alix Milan/Alix Milan/Views/KitHire/Category.cshtml
@model Alix_Milan.ViewModels.KitHireCategoryModel

@{
    ViewBag.Title = "Kit Hire - " + Model.Name;
    Layout = "~/Views/Shared/Front.cshtml";
}

<h1>@Model.Name</h1>

<div class="image">
    @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(Model.ImageBytes) + "\" />")
</div>

@if (Model.SubcategoryKitItems.SelectMany(sc => sc.Value).Any() || Model.MiscKitItems.Any())
{
    @Html.Partial("SubcategoryItems", Model)

    @Html.Partial("MiscKitItems", Model)
}
else
{
    <p>
        No items to display
    </p>
}

<p>
    @Html.ActionLink("Back to list", "")
</p>

Alix Milan/Alix Milan/Views/KitHire/Index.cshtml
@model Alix_Milan.ViewModels.KitHireModel
@{
    ViewBag.Title = "Kit Hire";
    Layout = "~/Views/Shared/Front.cshtml";
}

<h1>Kit Hire</h1>

@if (Model.Categories.Any())
{
    <h2>Categories</h2>
    foreach (var category in Model.Categories)
    {
        <a href='@Url.Action("Category", "KitHire", new { id = category.Name })' class="project">
            <div class="overlay">
                <h3>
                    @category.Name
                </h3>
                @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(category.ImageBytes) + "\" />")
            </div>
        </a>
    }
}

@if (Model.Kits.Any())
{
    <h2>Kits</h2>
    foreach (var kit in Model.Kits)
    {
        <a href='@Url.Action("Kit", "KitHire", new { id = kit.Name })' clas class="project">
            <div class="overlay">
                <h3>
                    @kit.Name
                </h3>
                @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(kit.ImageBytes) + "\" />")
            </div>
        </a>
    }
}

Alix Milan/Alix Milan/Views/KitHire/Kit.cshtml
@model Alix_Milan.ViewModels.KitModel

@{
    ViewBag.Title = "Kit Hire - " + Model.Name;
    Layout = "~/Views/Shared/Front.cshtml";
}

<h2>@Model.Name</h2>

@Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(Model.ImageBytes) + "\" />")

<p>@Model.Description</p>

<p>£@Model.Price</p>

<h3>Items</h3>

@if (Model.KitItems.Any())
{
    <table class="table">
        <tr>
            <th>
            </th>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
            </th>
        </tr>

        @foreach (var item in Model.KitItems)
        {
        <tr>
            <td>
                @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(item.ImageBytes) + "\" />")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                £@Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.RouteLink("View details", "KitItem", new { kitItemName = item.Name })
            </td>
        </tr>
        }

    </table>
}
else
{
    <p>
        This kit has no items
    </p>
}

<p>
    @Html.ActionLink("Back to List", "")
</p>

Alix Milan/Alix Milan/Views/KitHire/KitItem.cshtml
@model Alix_Milan.ViewModels.KitItemModel

@{
    ViewBag.Title = "Kit Hire - " + Model.Name;
    Layout = "~/Views/Shared/Front.cshtml";
}

<h2>@Model.Name</h2>

<div>
    <dl class="dl-horizontal">
        @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(Model.ImageBytes) + "\" />")

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            £@Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>

<p>
    @Html.ActionLink("Back to List", "")
</p>

Alix Milan/Alix Milan/Views/KitHire/MiscKitItems.cshtml
@model KitHireCategoryModel
@using Alix_Milan.ViewModels

@if (Model.MiscKitItems.Any())
{
    <h3>
        No Sub-Category
    </h3>

    <table class="table">
        <tr>
            <th>
            </th>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
            </th>
        </tr>

        @foreach (var item in Model.MiscKitItems)
        {
            <tr>
                <td>
                    @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(item.ImageBytes) + "\" />")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.RouteLink("View details", "KitItem", new { kitItemName = item.Name })
                </td>
            </tr>
        }
    </table>
}

Alix Milan/Alix Milan/Views/KitHire/SubcategoryItems.cshtml
@model KitHireCategoryModel
@using Alix_Milan.ViewModels

@foreach (var subcategory in Model.SubcategoryKitItems)
{

    if (subcategory.Value.Any())
    {
        <h3>
            @subcategory.Key.Name
        </h3>

        <table class="table">
            <tr>
                <th>
                </th>
                <th>
                    Name
                </th>
                <th>
                    Price
                </th>
                <th>
                </th>
            </tr>

            @foreach (var item in subcategory.Value)
            {
                <tr>
                    <td>
                        @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(item.ImageBytes) + "\" />")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        £@Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.RouteLink("View details", "KitItem", new { kitItemName = item.Name })
                    </td>
                </tr>
            }
        </table>
    }
}