Alix Milan/Alix Milan/Controllers/ManageCVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Alix_Milan;
using Alix_Milan.Models;
using Alix_Milan.ViewModels;
using System.IO;

namespace Alix_Milan.Controllers
{
    public class ManageCVController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: ManageCV
        public ActionResult Index()
        {
            return View(db.CVs.ToList());
        }

        // GET: ManageCV/View
        public ActionResult Details()
        {
            var cv = db.CVs.SingleOrDefault();

            if (cv == null)
            {
                return HttpNotFound();
            }

            MemoryStream output = new MemoryStream();
            output.Write(cv.File, 0, cv.File.Length);
            output.Position = 0;

            HttpContext.Response.AddHeader("content-disposition", "inline; filename=CV.pdf");

            // Return the output stream
            return File(output, "application/pdf"); 
        }

        // GET: ManageCV/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ManageCV/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,File")] EnterCV cv)
        {
            if (ModelState.IsValid == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            var newCV = new CV();

            if (cv.File != null && cv.File.ContentLength > 0)
            {
                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(cv.File.InputStream))
                {
                    fileData = binaryReader.ReadBytes(cv.File.ContentLength);
                }

                newCV.File = fileData;
            }

                db.CVs.Add(newCV);
                db.SaveChanges();
                return RedirectToAction("Index");
        }

        // GET: ManageCV/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            CV cv = db.CVs.Find(id);

            if (cv == null)
            {
                return HttpNotFound();
            }

            var cvViewModel = new EnterCV
            {
                ID = cv.ID,
                ExistingFile = cv.File
            };

            return View(cvViewModel);
        }

        // POST: ManageCV/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,File")] EnterCV cvViewModel)
        {
            var cv = db.CVs.Find(cvViewModel.ID);

            if (ModelState.IsValid == false || cv == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            if (cvViewModel.File != null && cvViewModel.File.ContentLength > 0)
            {
                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(cvViewModel.File.InputStream))
                {
                    fileData = binaryReader.ReadBytes(cvViewModel.File.ContentLength);
                }

                cv.File = fileData;
            }

            db.Entry(cv).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: ManageCV/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CV cV = db.CVs.Find(id);
            if (cV == null)
            {
                return HttpNotFound();
            }
            return View(cV);
        }

        // POST: ManageCV/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CV cV = db.CVs.Find(id);
            db.CVs.Remove(cV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Alix Milan/Alix Milan/Views/ManageCV/Create.cshtml
@model Alix_Milan.ViewModels.EnterCV

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Back.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "ManageCV", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="File" class="input-files" data-val="true" data-val-required="The File field is required." />
                @Html.ValidationMessageFor(model => model.File, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Alix Milan/Alix Milan/Views/ManageCV/Delete.cshtml
@model Alix_Milan.Models.CV

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Back.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CV</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.File)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Alix Milan/Alix Milan/Views/ManageCV/Edit.cshtml
@model Alix_Milan.ViewModels.EnterCV

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Back.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "ManageCV", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CV</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.File, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" class="input-files" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Alix Milan/Alix Milan/Views/ManageCV/Index.cshtml
@model IEnumerable<Alix_Milan.Models.CV>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Back.cshtml";
}

<h2>Index</h2>

@if (Model.Any() == false)
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.File)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details") |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>