Alix Milan/Alix Milan/Controllers/ManageKitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Alix_Milan;
using Alix_Milan.Models;
using Alix_Milan.ViewModels;
using System.IO;

namespace Alix_Milan.Controllers
{
    public class ManageKitsController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: ManageKits
        public ActionResult Index()
        {
            return View(db.Kits);
        }

        // GET: ManageKits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kit kit = db.Kits.Find(id);
            if (kit == null)
            {
                return HttpNotFound();
            }

            kit.KitItems = db.KitItems.Where(ki => ki.KitId == kit.ID);

            return View(kit);
        }

        // GET: ManageKits/Create
        public ActionResult Create()
        {
            var kitViewModel = new EnterKit
            {
                Categories = db.Categories.OrderBy(c => c.Order),
                SubCategories = db.SubCategories.OrderBy(sc => sc.Order)
            };

            return View(kitViewModel);
        }

        // POST: ManageKits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Description,Price,ImageFile")] EnterKit kitViewModel)
        {
            if (ModelState.IsValid == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            var kit = new Kit
            {
                Name = kitViewModel.Name,
                Description = kitViewModel.Description,
                Price = kitViewModel.Price.Value
            };

            if (kitViewModel.ImageFile != null && kitViewModel.ImageFile.ContentLength > 0)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(kitViewModel.ImageFile.InputStream))
                {
                    imageData = binaryReader.ReadBytes(kitViewModel.ImageFile.ContentLength);
                }

                kit.ImageBytes = imageData;
            }

            db.Kits.Add(kit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: ManageKits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Kit kit = db.Kits.Find(id);

            if (kit == null)
            {
                return HttpNotFound();
            }

            var kitViewModel = new EnterKit
            {
                ID = kit.ID,
                Name = kit.Name,
                Description = kit.Description,
                Price = kit.Price,
                Categories = db.Categories.OrderBy(c => c.Order),
                SubCategories = db.SubCategories.OrderBy(sc => sc.Order),
                ExistingImageBytes = kit.ImageBytes
            };

            return View(kitViewModel);
        }

        // POST: ManageKits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Description,Price,ImageFile")] EnterKit kitViewModel)
        {
            var kit = db.Kits.Find(kitViewModel.ID);

            if (ModelState.IsValid == false || kit == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            kit.Name = kitViewModel.Name;
            kit.Description = kitViewModel.Description;
            kit.Price = kitViewModel.Price.Value;

            if (kitViewModel.ImageFile != null && kitViewModel.ImageFile.ContentLength > 0)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(kitViewModel.ImageFile.InputStream))
                {
                    imageData = binaryReader.ReadBytes(kitViewModel.ImageFile.ContentLength);
                }

                kit.ImageBytes = imageData;
            }

            db.Entry(kit).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: ManageKits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kit kit = db.Kits.Find(id);
            if (kit == null)
            {
                return HttpNotFound();
            }
            return View(kit);
        }

        // POST: ManageKits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Kit kit = db.Kits.Find(id);
            db.Kits.Remove(kit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult GetSubCategories(string selection)
        {
            var subcategories = db.SubCategories.Where(sc => sc.CategoryId.ToString() == selection).OrderBy(sc => sc.Order).ToList();

            return Json(subcategories);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Alix Milan/Alix Milan/Views/ManageKits/Delete.cshtml
@model Alix_Milan.Models.Kit

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Back.cshtml";
}

<h2>Delete @Model.Name</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Alix Milan/Alix Milan/Views/ManageKits/Details.cshtml
@model Alix_Milan.Models.Kit

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Back.cshtml";
}

<h2>@Model.Name</h2>

<dl class="dl-horizontal">
    @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(Model.ImageBytes) + "\" />")
    
    <dt>
        @Html.DisplayNameFor(model => model.Description)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.Price)
    </dt>

    <dd>
        £@Html.DisplayFor(model => model.Price)
    </dd>
</dl>

<h3>Items</h3>
@if (Model.KitItems.Any())
{
    <table class="table">
        <tr>
            <th>
            </th>
            <th>
                Name
            </th>
            <th>
                Price
            </th>
            <th>
            </th>
        </tr>

        @foreach (var item in Model.KitItems)
        {
            <tr>
                <td>
                    @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(item.ImageBytes) + "\" />")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    £@Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.ActionLink("View details", "Details", "ManageKitItems", new { @id= item.ID }, null)
                </td>
            </tr>
        }

    </table>
}
else
{
    <p>
        This kit has no items
    </p>
}

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Alix Milan/Alix Milan/Views/ManageKits/Edit.cshtml
@model Alix_Milan.ViewModels.EnterKit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Back.cshtml";
}

<h2>Edit @Model.Name</h2>

@using (Html.BeginForm("Edit", "ManageKits", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExistingImageBytes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(Model.ExistingImageBytes) + "\" />")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" class="input-files" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Alix Milan/Alix Milan/Views/ManageKits/Index.cshtml
@model IEnumerable<Alix_Milan.Models.Kit>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Back.cshtml";
}

<h2>Manage Kits</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.Raw("<img src=\"data:image/jpeg;base64," + Convert.ToBase64String(item.ImageBytes) + "\" />")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <th>
                £@Html.DisplayFor(modelItem => item.Price)
            </th>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>